train_dataset: FC100
train_dataset_args: {split: train, augment: resize}
fs_dataset: FC100
fs_dataset_args: {split: test}
eval_fs_epoch: 5

model: classifier
model_args:
    encoder: resnet12
    encoder_args: {}
    classifier: linear-classifier
    classifier_args: {n_classes: 60}

batch_size: 64
max_epoch: 65
optimizer: sgd
optimizer_args: {lr: 0.05, weight_decay: 5.e-4, milestones: [60], gamma: 0.1}

save_epoch: 5
